### PR TITLE
Add Holopin as partner and Clare McCann as team member

### PR DESCRIPTION
**Pull request by smoia**
Also doing all of this in the wrongest way possible by merging main from main :eyes:
(Don't judge me, didn't have :coffee: yet)

### CODE REVIEW

**Comment by smoia** [comment]
@clarefmccann be aware that this exists :eyes:

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
I think you should remove the avatar.jpg if we want the website to use the github avatar profile instead

**Comment by Remi-Gau** [comment]
> Also doing all of this in the wrongest way possible by merging main from main eyes (Don't judge me, didn't have coffee yet)

hahaha 

I was literally pushing to main yesterday on the brainhack jupyter book repo, so I would be hypocrite, if I said anything about this

**Comment by Remi-Gau** [comment]
and of course I tried to push something on your main that borked everything... Sorry

**Pull request closed without merging**
